In [3]:
print("""My name is kazi Tanzizul Haque.
I am a student of Aiub""")
print("Id",input())

My name is kazi Tanzizul Haque.
I am a student of Aiub
22-47783-2
Id 22-47783-2


In [7]:
A=[x**2 for x in range(10) if x%2==0]
print(A)

[0, 4, 16, 36, 64]


In [40]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.arange(8)
c=np.arange(8).reshape(2,4)
print(A)
print(b)
print(c)
d=A[:3,1:3]
print(d)

Tan=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

#print(Tan[[0,1,2,3],[0,0,0,0]])
print()
print(np.array([Tan[0,0],Tan[1,0],Tan[2,0],Tan[3,0]]))
zil=np.array([0,0,0,0])
print(Tan[np.arange(4),zil])

x=np.full((3,3),7)
print(x)

y=np.random.random((3,3))
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[0 1 2 3 4 5 6 7]
[[0 1 2 3]
 [4 5 6 7]]
[[2 3]
 [5 6]
 [8 9]]

[ 1  4  7 10]
[ 1  4  7 10]
[[7 7 7]
 [7 7 7]
 [7 7 7]]
[[0.25055841 0.55549792 0.13083081]
 [0.18805839 0.43391123 0.88498795]
 [0.39162767 0.20255576 0.43114469]]


In [25]:
x=np.array([1,2,3,4,5,6,222,343,5,23])
print(max(x))

343


In [30]:
z=np.array([[3,1,4,2],[12,3,4,52],[2,3,4,2]])

bool_index=(z>2)
print(bool_index)
print(z[bool_index])

[[ True False  True False]
 [ True  True  True  True]
 [False  True  True False]]
[ 3  4 12  3  4 52  3  4]


In [37]:
a=np.array([[1,2],[3,4]], dtype=np.float64)
b=np.array([[2,3],[4,5]],dtype=np.int32)

print(np.add(a,b))

print(a+b)

[[3. 5.]
 [7. 9.]]
[[3. 5.]
 [7. 9.]]


In [38]:
a=np.array([[1,2],[3,4]])
b=np.array([[2,3],[4,5]])

print(np.dot(a,b))

[[10 13]
 [22 29]]


In [48]:
x=np.array([[2,3],[4,5]])
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x,axis=1))

print(np.mean(x))
print(np.mean(x, axis=1))
print()
print(x)
print()
print(x.T)

v=np.array([1,2,3])

print(v)
print(v.T)

14
[6 8]
[5 9]
3.5
[2.5 4.5]

[[2 3]
 [4 5]]

[[2 4]
 [3 5]]
(3,)
[1 2 3]
[1 2 3]
(3,)


# **Broadcasting**

In [49]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [51]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y=np.empty_like(x)

for i in range(4):
  y[ i, :]=x[i,:]+v
print(y)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]
